server:
  port: 8080

management:
  metrics:
    export:
      wavefront:
        enabled: false

spring:
  main:
    allow-bean-definition-overriding: true  
  profiles:
    active: 
      - acceptance
    include:
      - gtb
      - ran
      - pln
      - xrs
      - sam     
  application:
    name: customer-asset-list-examiner-api
logging:
  pattern:
    console: "%d{UNIX_MILLIS} %5p %t %c{1} ${spring.application.name:-} p:%X{prv}|c:%X{cst}|u:%X{usr} - %m%n"
    file: "%d{UNIX_MILLIS} %5p %t %c{1} ${spring.application.name:-} p:%X{prv}|c:%X{cst}|u:%X{usr} - %m%n"
  level:
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: TRACE
cf-foundation:
  pbe:
    secretKey: "mZQqICrxVE"
  navigation-links:
    enable: true
    default-page: 0
    default-page-size: 100
  error-detail:
    enable: true
  enhanced-logging:
    enable-mdc-logging: true
    enable-exception-detail-logging: true
    enable-request-data-logging: false
    enable-exception-request-data-logging: true    
    http-request-headers:
      - X-PNSK-API-ENABLE-ERROR-VERBOSITY
      - X-PNSK-API-REQUEST-TRACKING-ID
      - X-PNSK-API-LOG-PAYLOAD
      - X-PNSK-CTX-CST
      - X-PNSK-CTX-PRV
      - host
      - accept-encoding
      - user-agent
      - connection
      - accept
      - cache-control
    http-response-headers:
      - Content-Type
  tracing:
    enable: true

  security:
    type: JWT
    token:
      secretkey: "ewogICAgInNoYXJlZF9hcGktYXV0aF9zZWNyZXRrZXkiOiAib2VSYVlZN1dvMjRzRHFLU1gzSU05QVNHbWRHUG1rVGQ5am8xUVR5NGI3UDlaZTVfOWhLb2xWWDh4TnJRRGNOUmZWRWRUWk5PdU95cUVHaFhFYmRKSS1aUTE5a19vOU1JMHkzZVpOMmxwOWpvdzU1RmZYTWlJTkVkdDFYUjg1VmlwUkxTT2tUNmtTcHpzMngtamJMRGl6OWlGVnprZDgxWUt4TWdQQTdWZlplUVVtNG4tbU9tbldNYVZYMzB6R0ZVNEwzb1BCY3RZS2tsNGRZZnFZV3FSTmZyZ1BKVm"
      expirationseconds: 43200 # 12 hours
  http:
    client:
      enable: true
      
penske-web-error:
    defaultDefinition:
        httpErrorCode: 503
        isTransient: false
        payloadErrorCode: server.internal.error
        payloadErrorMessage: The server failed to process this request, If the problem persists please contact us with the request tracking id in the http header
    definitions:
    -   exceptionClassName: java.lang.NullPointerException,
        payloadErrorCode: developer.bug.encountered
    -   exceptionClassName: org.springframework.http.converter.HttpMessageNotReadableException
        payloadErrorCode: request.format.invalid
        payloadErrorMessage: The request is malformed and does not meet the expected schema
    validationDefault:
        httpErrorCode: 400
        payloadErrorCode: order.request.invalid

unit-api:
  by-vin-route:  https://ms-unit-api-acp-qa.acp.ptlapps.com/v1/units
  get-dataproviders: https://cid-api-qa-t4-acp.acp.ptlapps.com/v1/enrollment/customers/providers
provider-api:
  get-provider-customers: https://ms-data-provider-api.acp.ptlapps.com/v1/providers/{providerCode}/customerConfigurations
#includes all database properties
cf-customer:
  datasource:
     jdbc-url: jdbc:mysql://cf-operational-hub.cluster-cxiw7em8bs29.us-east-1.rds.amazonaws.com:3306/cf_data_provider
     username: data-provider-apis
     password: S6ARxKZS23sbaHB5x2dg
cf-staging:
  datasource:
    jdbc-url: jdbc:mysql://cf-operational-hub.cluster-cxiw7em8bs29.us-east-1.rds.amazonaws.com:3306/cf_data_provider
    username: data-provider-apis
    password: S6ARxKZS23sbaHB5x2dg
MAX_NUM_MASTERIDS: 50